version: '1.0.{build}'

image: 
    - Visual Studio 2017
    - Visual Studio 2015

cache:
    - C:\projects\aditof-sdk\deps -> ci\appveyor\install_glog.bat
    - C:\tools\opencv -> ci\appveyor\install_opencv.bat

install:
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (
            set generator=Visual Studio 14 2015
        ) else if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (
            set generator=Visual Studio 15 2017
        )
    #- set generator=%generator:"=%
    - if not exist "deps" ( mkdir deps )
    - C:\projects\aditof-sdk\ci\appveyor\install_opencv.bat
    - cd %APPVEYOR_BUILD_FOLDER%


build_script:

    # x64 glog install
    - C:\projects\aditof-sdk\ci\appveyor\install_glog.bat "Release" "Win64"
    - C:\projects\aditof-sdk\ci\appveyor\install_glog.bat "Debug" "Win64"
    
    # x64
    - mkdir build
    - ps: pushd build
    - cmake -G "%generator% Win64" -DOpenCV_DIR="C:\tools\opencv\build\x64\vc15\lib" ..
    - cmake --build . --config "Release"
    - ps: popd
    - mkdir build_debug
    - ps: pushd build_debug
    - cmake -G "%generator% Win64" -DOpenCV_DIR="C:\tools\opencv\build\x64\vc15\lib" ..
    - cmake --build . --config "Debug"
    - ps: popd

    # x32 glog install
    - C:\projects\aditof-sdk\ci\appveyor\install_glog.bat "Release"
    - C:\projects\aditof-sdk\ci\appveyor\install_glog.bat "Debug"

    # x32
    - mkdir build_x32
    - ps: pushd build_x32
    - cmake -G "%generator%" -DWITH_EXAMPLES=off ..
    - cmake --build . --config "Release"
    - ps: popd
    - mkdir build_debug_x32
    - ps: pushd build_debug_x32
    - cmake -G "%generator%" -DWITH_EXAMPLES=off ..
    - cmake --build . --config "Debug"
    - ps: popd

after_build:
    - cinst InnoSetup
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( 
        C:\projects\aditof-sdk\ci\appveyor\make_installer.bat
      )
    - C:\projects\aditof-sdk\ci\appveyor\make_zip.bat
